set nocompatible
syntax on
set mouse=
set ttymouse=
set background=dark
colorscheme cyberpunkneon
filetype plugin indent on
set grepprg=grep\ -nH\ $*
let g:tex_flavor = "latex"
set runtimepath=~/.vim,$VIM/vimfiles,$VIMRUNTIME,$VIM/vimfiles/after,~/.vim/after
